---
defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make lint

workflows:
  version: 2
  branch:
    jobs:
      - lint:
          filters:
            branches:
              only: /.*/
